### ISSUE TITLE
Tried to install django-webodt via pip and then from tar

### ISSUE THREAD

**Issue by jheld** [NetAngels/django-webodt#3]
Error: No module named preprocessors

Something about C in this. I'm really unsure where to go from here. I'd love to use this app since it should help me with my online doc app.

Thanks for any help--I hope it's really simple. I have installed apps before and have never had this issue.

**Comment by imankulov** [comment]
For some reason the package published at pypi has accidentally missed a number of python files. I'm very sorry about it, I've just fixed the issue and released new version 0.3.1.

By the way. The problem is not related to C at all, it's all about [webodt preprocessors](/NetAngels/django-webodt/blob/master/webodt/preprocessors.py), functions altering ODF templates prior to pass them to django Template() constructor. The idea behind preprocessors is to allow one to write templates using Django syntax right into word processor.

Currently there is not much of documentation about this feature, but [this example](http://packages.python.org/django-webodt/tables.html) probably make it more clear.

Thanks for using webodt package, and particularly thank you for your feedback.
